// app/data.ts

export interface Exhibit {
  id: string;
  name: string;
  category: string;
  subcategory: string;
  description: string;
  traits: string[];
  source: string;
  base_buzz: number;
  max_buzz: number;
  max_knowledge: number;
  image_url?: string;
}

export const EXHIBITS_DATA: Exhibit[] = [
  // --- 史前 / 化石 ---
  { id: "1", name: "灯笼鱼化石", category: "史前", subcategory: "化石", traits: ["无"], description: "", source: "双点海, 白骨带 - 永逝之湖, 湿特兰蒂斯荒野", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "2", name: "左脚印化石", category: "史前", subcategory: "化石", traits: ["无"], description: "", source: "白骨带 - 远古遗迹", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "3", name: "异次元时光队长化石", category: "史前", subcategory: "化石", traits: ["无"], description: "", source: "白骨带 - 迷乱沙丘", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "4", name: "右脚印化石", category: "史前", subcategory: "化石", traits: ["无"], description: "", source: "白骨带 - 黑糖浆湖", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "5", name: "软盘化石", category: "史前", subcategory: "化石", traits: ["无"], description: "", source: "白骨带 - 焦油旷野", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "6", name: "异星化石", category: "史前", subcategory: "化石", traits: ["无"], description: "", source: "白骨带 - 焦油旷野", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "7", name: "甲壳化石", category: "史前", subcategory: "化石", traits: ["无"], description: "", source: "白骨带 - 焦油旷野", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  // --- 史前 / 恐龙骨架 ---
  { id: "8", name: "小恶龙骨架", category: "史前", subcategory: "恐龙骨架", traits: ["特别访客加成"], description: "", source: "白骨带 - 飞龙之路", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "9", name: "恶龙骨架", category: "史前", subcategory: "恐龙骨架", traits: ["特别访客加成", "腹泻的幽默"], description: "", source: "白骨带 - 阴云山", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "10", name: "双头斗龙骨架", category: "史前", subcategory: "恐龙骨架", traits: ["无"], description: "", source: "白骨带 - 庞然巨岩", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "11", name: "皇冠霸王龙骨架", category: "史前", subcategory: "恐龙骨架", traits: ["无"], description: "", source: "白骨带 - 霸王龙岩", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "12", name: "独角骨架", category: "史前", subcategory: "恐龙骨架", traits: ["无"], description: "", source: "白骨带 - 终焉之境", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "13", name: "霸王蝎短尾翼独角龙", category: "史前", subcategory: "恐龙骨架", traits: ["无"], description: "", source: "白骨带 - 终焉之境", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "14", name: "多头水龙骨架", category: "史前", subcategory: "恐龙骨架", traits: ["无", "腹泻的幽默"], description: "好笑的惊吓方式，轻微影响肠胃舒适度", source: "双点海, 白骨带 - 永逝之湖, 浸水岩洞", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "15", name: "雪嚎龙骨架", category: "史前", subcategory: "恐龙骨架", traits: ["无"], description: "", source: "白骨带 - 冰霜之巅", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "16", name: "咬咬龙骨架", category: "史前", subcategory: "恐龙骨架", traits: ["无"], description: "", source: "白骨带 - 啃噬之森", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "17", name: "指挥家巨蟒骨架", category: "史前", subcategory: "恐龙骨架", traits: ["无"], description: "", source: "白骨带 - 腐臭小径", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "18", name: "振翅翼龙骨架", category: "史前", subcategory: "恐龙骨架", traits: ["无", "腹泻的幽默"], description: "好笑的惊吓方式，轻微影响肠胃舒适度", source: "白骨带 - 腐臭小径", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "19", name: "迅爬龙骨架", category: "史前", subcategory: "恐龙骨架", traits: ["无"], description: "", source: "白骨带 - 凋零之路", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "20", name: "尖背龙骨架", category: "史前", subcategory: "恐龙骨架", traits: ["无"], description: "", source: "白骨带 - 肋骨荒原", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "21", name: "石甲犰狳骨架", category: "史前", subcategory: "恐龙骨架", traits: ["无"], description: "", source: "白骨带 - 肋骨荒原", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "22", name: "鳄龙骨", category: "史前", subcategory: "恐龙骨架", traits: ["无"], description: "", source: "双点海 - 白骨浅滩", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  // --- 史前 / 封存文物 ---
  { id: "23", name: "恐龙琥珀", category: "史前", subcategory: "封存文物", traits: ["无"], description: "", source: "白骨带 - 远古淡黄穹顶", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "24", name: "暴爬龙琥珀", category: "史前", subcategory: "封存文物", traits: ["无"], description: "", source: "白骨带 - 远古淡黄穹顶", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "25", name: "蜜封蜂蜜", category: "史前", subcategory: "封存文物", traits: ["无"], description: "", source: "白骨带 - 焦油旷野", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "26", name: "琥珀巨蛋", category: "史前", subcategory: "封存文物", traits: ["无"], description: "", source: "白骨带 - 黑糖浆湖", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "27", name: "大型壁虎琥珀", category: "史前", subcategory: "封存文物", traits: ["无"], description: "", source: "白骨带 - 黑糖浆湖", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  // --- 史前 / 冰封珍品 ---
  { id: "28", name: "冰晶", category: "史前", subcategory: "冰封珍品", traits: [], description: "", source: "白骨带 - 毛绒山峰", base_buzz: 60, max_buzz: 190, max_knowledge: 0 },
  { id: "29", name: "冰封蜂巢", category: "史前", subcategory: "冰封珍品", traits: ["冰封"], description: "维护度降为0%时会发生融化，解冻的展示品只能进行出售", source: "白骨带 - 寒冷矿洞", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "30", name: "冰封穴居人", category: "史前", subcategory: "冰封珍品", traits: ["冰封"], description: "维护度降为0%时会发生融化，解冻的展示品只能进行出售", source: "白骨带 - 寒冷矿洞", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "31", name: "冰封冰箱", category: "史前", subcategory: "冰封珍品", traits: ["冰封"], description: "维护度降为0%时会发生融化，解冻的展示品只能进行出售", source: "双点海, 白骨带 - 寒冷矿洞, 极暗深渊", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "32", name: "冰冻连眉巨怪", category: "史前", subcategory: "冰封珍品", traits: ["冰封"], description: "维护度降为0%时会发生融化，解冻的展示品只能进行出售", source: "白骨带 - 冰霜之巅", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "33", name: "冰封灯笼鱼", category: "史前", subcategory: "冰封珍品", traits: ["冰封"], description: "维护度降为0%时会发生融化，解冻的展示品只能进行出售", source: "双点海 - 极暗深渊", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  // --- 史前 / 史前奥秘 ---
  { id: "34", name: "洞穴墙面壁画", category: "史前", subcategory: "史前奥秘", traits: ["史前奥秘", "远古广告"], description: "有来自其他时空或地点的古怪标记,跨越时空全方位宣传博物馆", source: "白骨带 - 庞然巨岩", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "35", name: "洞穴转角壁画", category: "史前", subcategory: "史前奥秘", traits: ["史前奥秘", "远古广告"], description: "有来自其他时空或地点的古怪标记,跨越时空全方位宣传博物馆", source: "白骨带 - 远古遗迹", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "36", name: "远古祭台", category: "史前", subcategory: "史前奥秘", traits: ["史前奥秘", "宇宙制造"], description: "有来自其他时空或地点的古怪标记,可生成装饰物品", source: "白骨带 - 原始边境", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "37", name: "时光通道", category: "史前", subcategory: "史前奥秘", traits: ["史前奥秘", "时间之门"], description: "有来自其他时空或地点的古怪标记,一扇十分有用的门，通往黎明时分", source: "白骨带 - 异次元时光, 迷乱沙丘", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "38", name: "孤独的石碑", category: "史前", subcategory: "史前奥秘", traits: ["史前奥秘"], description: "有来自其他时空或地点的古怪标记", source: "白骨带 - 迷乱沙丘", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "39", name: "远古虚构解剖器", category: "史前", subcategory: "史前奥秘", traits: [], description: "", source: "其他", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  // --- 史前 / 古代发明 ---
  { id: "40", name: "熔岩灯", category: "史前", subcategory: "古代发明", traits: ["望而生畏", "有趣", "令人好奇的"], description: "可对犯罪行动产生震慑效果,提升访客的娱乐度,提供的知识额外+1", source: "双点海, 白骨带 - 火山温泉, 荒蛮峭壁", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "41", name: "石制音响", category: "史前", subcategory: "古代发明", traits: ["望而生畏", "有趣", "令人好奇的"], description: "可对犯罪行动产生震慑效果,提升访客的娱乐度,提供的知识额外+1", source: "白骨带 - 白费镇与徒劳镇的交界之地", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "42", name: "岩石躺椅", category: "史前", subcategory: "古代发明", traits: ["望而生畏", "有趣", "令人好奇的"], description: "可对犯罪行动产生震慑效果,提升访客的娱乐度,提供的知识额外+1", source: "白骨带 - 白费镇与徒劳镇的交界之地", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "43", name: "原始计算机", category: "史前", subcategory: "古代发明", traits: ["望而生畏", "有趣", "令人好奇的"], description: "可对犯罪行动产生震慑效果,提升访客的娱乐度,提供的知识额外+1", source: "白骨带 - 白费镇与徒劳镇的交界之地", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "44", name: "远古打地鼠", category: "史前", subcategory: "古代发明", traits: ["望而生畏", "有趣", "令人好奇的"], description: "可对犯罪行动产生震慑效果,提升访客的娱乐度,提供的知识额外+1", source: "白骨带 - 隐士山丘", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "45", name: "贝壳电话", category: "史前", subcategory: "古代发明", traits: ["望而生畏", "有趣", "令人好奇的"], description: "可对犯罪行动产生震慑效果,提升访客的娱乐度,提供的知识额外+1", source: "白骨带 - 隐士山丘", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  // --- 自然 / 食人植物 ---
  { id: "46", name: "马戏团小丑花", category: "自然", subcategory: "食人植物", traits: ["植物出品（小丑）", "生老病死"], description: "偶尔会吞掉访客，把他们变成小丑,健康度降至0%时会死亡/枯萎", source: "冥界, 白骨带 - 冥界展会", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "47", name: "食人花折叠椅", category: "自然", subcategory: "食人植物", traits: ["生老病死"], description: "健康度降至0%时会死亡/枯萎", source: "白骨带 - 大脚花园", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "48", name: "食人花陷阱", category: "自然", subcategory: "食人植物", traits: ["生老病死"], description: "健康度降至0%时会死亡/枯萎", source: "白骨带 - 食人花丛林", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "49", name: "小食人花", category: "自然", subcategory: "食人植物", traits: ["生老病死"], description: "健康度降至0%时会死亡/枯萎", source: "白骨带 - 食人花丛林", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "50", name: "血蝠树", category: "自然", subcategory: "食人植物", traits: ["植物出品（吸血鬼）", "生老病死"], description: "偶尔会吞掉访客，把他们变成吸血鬼,健康度降至0%时会死亡/枯萎", source: "冥界 - 死神农园", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  // --- 自然 / 热带植物 ---
  { id: "51", name: "婆娑树", category: "自然", subcategory: "热带植物", traits: ["生老病死"], description: "健康度降至0%时会死亡/枯萎", source: "白骨带 - 沉寂河流", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "52", name: "恶臭花", category: "自然", subcategory: "热带植物", traits: ["恶臭孢子", "生老病死"], description: "健康度低下时会散发出难闻的气味，降低周围人的环境值,健康度降至0%时会死亡/枯萎", source: "白骨带 - 啃噬之森", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "53", name: "棕榈树", category: "自然", subcategory: "热带植物", traits: ["生老病死"], description: "健康度降至0%时会死亡/枯萎", source: "双点海 - 茂林镇丛林", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  // --- 自然 / 食用植物 ---
  { id: "54", name: "蛋糕树", category: "自然", subcategory: "食用植物", traits: ["蛋糕果"], description: "增加吃饱度和娱乐度，但减少肠胃舒适度", source: "白骨带 - 草本绿野", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "55", name: "常青香肠树", category: "自然", subcategory: "食用植物", traits: ["香肠果"], description: "增加吃饱度，但减少肠胃舒适度", source: "白骨带 - 草本绿野", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "56", name: "糖浆树", category: "自然", subcategory: "食用植物", traits: ["糖浆果", "生老病死"], description: "增加喝饱度，但减少肠胃舒适度,健康度降至0%时会死亡/枯萎", source: "白骨带 - 白费镇与徒劳镇的交界之地", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "57", name: "壶龙果", category: "自然", subcategory: "食用植物", traits: ["壶龙果", "生老病死"], description: "增加喝饱度，但减少肠胃舒适度,健康度降至0%时会死亡/枯萎", source: "白骨带 - 沉寂河流", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "58", name: "刺头梨", category: "自然", subcategory: "食用植物", traits: ["刺头果"], description: "增加吃饱度，但减少肠胃舒适度", source: "低端科技地穴 - 植地实验室", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  // --- 自然 / 高山植物 ---
  { id: "59", name: "爬山花", category: "自然", subcategory: "高山植物", traits: ["生老病死"], description: "健康度降至0%时会死亡/枯萎", source: "白骨带 - 荒蛮峭壁", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "60", name: "极光树", category: "自然", subcategory: "高山植物", traits: ["生老病死"], description: "健康度降至0%时会死亡/枯萎", source: "白骨带 - 原始边境", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "61", name: "魂树", category: "自然", subcategory: "高山植物", traits: ["生老病死"], description: "健康度降至0%时会死亡/枯萎", source: "冥界 - 迷雾沼泽", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "62", name: "寒椒树", category: "自然", subcategory: "高山植物", traits: ["生老病死", "冰封"], description: "健康度降至0%时会死亡/枯萎,维护度降为0%时会发生融化，解冻的展示品只能进行出售", source: "低端科技地穴, 冥界 - 低温实验室, 寒冰尖塔", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "63", name: "窥视睡莲", category: "自然", subcategory: "高山植物", traits: ["生老病死"], description: "健康度降至0%时会死亡/枯萎", source: "双点海 - 佩博里海岸", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "64", name: "偷窥莲叶", category: "自然", subcategory: "高山植物", traits: ["生老病死"], description: "健康度降至0%时会死亡/枯萎", source: "已知宇宙 - 星莲平台", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "65", name: "囚藤毒蔓", category: "自然", subcategory: "高山植物", traits: [], description: "", source: "焦土世界 - 积云森林", base_buzz: 54, max_buzz: 178, max_knowledge: 0 },
  // --- 自然 / 外来花卉 ---
  { id: "66", name: "复制树屋", category: "自然", subcategory: "外来花卉", traits: ["生老病死"], description: "健康度降至0%时会死亡/枯萎", source: "冥界 - 蘑菇荒原", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "67", name: "蹦床花", category: "自然", subcategory: "外来花卉", traits: ["生老病死"], description: "健康度降至0%时会死亡/枯萎", source: "冥界 - 蘑菇荒原", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  // --- 海洋 / 热带鱼类 ---
  { id: "68", name: "旅行鱼", category: "海洋", subcategory: "热带鱼类", traits: ["无"], description: "", source: "白骨带 - 阳沁河溪", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "69", name: "狡猾蜥", category: "海洋", subcategory: "热带鱼类", traits: ["无"], description: "", source: "白骨带 - 阳沁河溪", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "70", name: "冰棍鱼", category: "海洋", subcategory: "热带鱼类", traits: ["无"], description: "", source: "白骨带 - 阳沁河溪", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "71", name: "隐士龟", category: "海洋", subcategory: "热带鱼类", traits: ["外壳", "生老病死"], description: "通过坚硬或带刺的外壳保护自身不被吃掉,健康度降至0%时会死亡/枯萎", source: "双点海 - 海洋枢纽", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "72", name: "狮头鱼", category: "海洋", subcategory: "热带鱼类", traits: ["海鲜主义者", "生老病死"], description: "偶尔会吃掉其他更小的鱼，慎重为其安排住处,健康度降至0%时会死亡/枯萎", source: "双点海 - 海洋枢纽", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "73", name: "猛虎鲨", category: "海洋", subcategory: "热带鱼类", traits: ["海鲜主义者", "水中恶霸", "生老病死"], description: "偶尔会吃掉其他更小的鱼，慎重为其安排住处,吓得人完全不敢靠近水,健康度降至0%时会死亡/枯萎", source: "双点海 - 昏暗浊海", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "74", name: "光谱鲟", category: "海洋", subcategory: "热带鱼类", traits: ["海味珍馐", "收藏家之选", "生老病死"], description: "偶尔会产出彩虹鱼子酱，员工会进行收集并出售,珍贵的个体，必将升值,健康度降至0%时会死亡/枯萎", source: "双点海 - 浸水岩洞", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "75", name: "脆脆鱼", category: "海洋", subcategory: "热带鱼类", traits: ["食用级品质", "生老病死"], description: "死亡不会降低售价,健康度降至0%时会死亡/枯萎", source: "双点海 - 火山温泉", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "76", name: "星鱼", category: "海洋", subcategory: "热带鱼类", traits: ["自带晚餐", "生老病死"], description: "自动觅食，不需要投放器,健康度降至0%时会死亡/枯萎", source: "双点海 - 佩博里礁", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "77", name: "浮夸鱼", category: "海洋", subcategory: "热带鱼类", traits: ["海洋美景", "生老病死"], description: "漂亮的鱼会让人联想到碧波荡漾的大海，从而提升环境值,健康度降至0%时会死亡/枯萎", source: "双点海 - 佩博里礁", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  // --- 海洋 / 温带鱼类 ---
  { id: "78", name: "抽象侧目鱼", category: "海洋", subcategory: "温带鱼类", traits: ["浑水之鱼", "生老病死"], description: "弄脏水族箱的速度更快，十分考验过滤能力,健康度降至0%时会死亡/枯萎", source: "双点海 - 潮汐山崖, 贪食洞窟", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "79", name: "蛮牛鲨", category: "海洋", subcategory: "温带鱼类", traits: ["海鲜主义者", "生老病死"], description: "偶尔会吃掉其他更小的鱼，慎重为其安排住处,健康度降至0%时会死亡/枯萎", source: "双点海 - 潮汐山崖", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "80", name: "黄金鱼", category: "海洋", subcategory: "温带鱼类", traits: ["收藏家之选", "生老病死"], description: "珍贵的个体，必将升值,健康度降至0%时会死亡/枯萎", source: "双点海 - 湿特兰蒂斯藏宝所", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "81", name: "水龙", category: "海洋", subcategory: "温带鱼类", traits: ["海洋美景", "生老病死"], description: "漂亮的鱼会让人联想到碧波荡漾的大海，从而提升环境值,健康度降至0%时会死亡/枯萎", source: "双点海 - 海藻林", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "82", name: "海马", category: "海洋", subcategory: "温带鱼类", traits: ["吃货", "生老病死"], description: "比预想中吃得更多，提升食物投放器的消耗速度,健康度降至0%时会死亡/枯萎", source: "双点海 - 海藻林", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "83", name: "飞鱼", category: "海洋", subcategory: "温带鱼类", traits: ["吃货", "生老病死"], description: "比预想中吃得更多，提升食物投放器的消耗速度,健康度降至0%时会死亡/枯萎", source: "双点海 - 霍格斯波特半岛", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "84", name: "充气鱼", category: "海洋", subcategory: "温带鱼类", traits: ["外壳", "生老病死"], description: "通过坚硬或带刺的外壳保护自身不被吃掉,健康度降至0%时会死亡/枯萎", source: "双点海 - 霍格斯波特半岛", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "85", name: "小丑鱼", category: "海洋", subcategory: "温带鱼类", traits: ["水中痴鱼", "生老病死"], description: "傻乐的鱼儿有什么不好？,健康度降至0%时会死亡/枯萎", source: "双点海 - 霍格斯波特半岛", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "86", name: "剑鱼", category: "海洋", subcategory: "温带鱼类", traits: [], description: "", source: "焦土世界 - 暴雨港", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  // --- 海洋 / 冷水鱼类 ---
  { id: "87", name: "机灵鲸", category: "海洋", subcategory: "冷水鱼类", traits: ["文化单一性"], description: "只愿意和同种类的鱼一起生活", source: "双点海 - 湿特兰蒂斯之底", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "88", name: "灯笼鱼", category: "海洋", subcategory: "冷水鱼类", traits: ["海鲜主义者", "生老病死"], description: "偶尔会吃掉其他更小的鱼，慎重为其安排住处,健康度降至0%时会死亡/枯萎", source: "双点海 - 极暗深渊", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "89", name: "水中死神", category: "海洋", subcategory: "冷水鱼类", traits: ["文化单一性"], description: "只愿意和同种类的鱼一起生活", source: "冥界, 双点海 - 墓地浅滩, 极暗深渊", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "90", name: "抹布鱼", category: "海洋", subcategory: "冷水鱼类", traits: ["清理大师", "自带晚餐", "生老病死"], description: "协助清理水族箱，提供更多过滤能力,自动觅食，不需要投放器,健康度降至0%时会死亡/枯萎", source: "双点海 - 麻木沉渊", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "91", name: "手握寿司鱼", category: "海洋", subcategory: "冷水鱼类", traits: ["食用级品质", "生老病死"], description: "死亡不会降低售价,健康度降至0%时会死亡/枯萎", source: "双点海 - 麻木沉渊", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "92", name: "豹鲨", category: "海洋", subcategory: "冷水鱼类", traits: ["海鲜主义者", "水中恶霸", "生老病死"], description: "偶尔会吃掉其他更小的鱼，慎重为其安排住处,吓得人完全不敢靠近水,健康度降至0%时会死亡/枯萎", source: "双点海 - 冰点洞穴", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "93", name: "蜘蛛蟹", category: "海洋", subcategory: "冷水鱼类", traits: ["浑水之鱼"], description: "弄脏水族箱的速度更快，十分考验过滤能力", source: "冥界, 双点海 - 冰点洞穴, 墓地浅滩, 极暗深渊", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "94", name: "海滩猫头鹰", category: "海洋", subcategory: "冷水鱼类", traits: ["自带晚餐"], description: "自动觅食，不需要投放器", source: "双点海 - 凝胶峡谷", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "95", name: "水母", category: "海洋", subcategory: "冷水鱼类", traits: ["自带晚餐"], description: "自动觅食，不需要投放器", source: "双点海 - 凝胶峡谷", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  // --- 海洋 / 海怪 ---
  { id: "96", name: "涂鸦乌贼", category: "海洋", subcategory: "海怪", traits: ["眼前一黑"], description: "会把水族箱染得黑黑的，员工进入水族箱后，能量将会减少", source: "双点海 - 湿特兰蒂斯荒野", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "97", name: "闪电鱼", category: "海洋", subcategory: "海怪", traits: ["吸取能量", "生老病死"], description: "员工进入水族箱后，能量将会减少,健康度降至0%时会死亡/枯萎", source: "双点海 - 昏暗浊海", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "98", name: "礁湖人", category: "海洋", subcategory: "海怪", traits: ["脚底抹油", "生物的悲哀"], description: "健康度将至0%时会逃离博物馆,初级员工进入水族箱后，幸福感将会减少", source: "双点海 - 贪食洞窟", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "99", name: "鱼人", category: "海洋", subcategory: "海怪", traits: [], description: "", source: "焦土世界 - 崎岖之路", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  // --- 海洋 / 湿特兰蒂斯文物 ---
  { id: "100", name: "湿特兰蒂斯之船", category: "海洋", subcategory: "湿特兰蒂斯文物", traits: ["无聊", "有趣", "令人好奇的", "腹泻的幽默", "望而生畏"], description: "减少访客的娱乐度,提升访客的娱乐度,提供的知识额外+1,好笑的惊吓方式，轻微影响肠胃舒适度,可对犯罪行动产生震慑效果", source: "双点海 - 湿特兰蒂斯荒野", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "101", name: "贝壳号角", category: "海洋", subcategory: "湿特兰蒂斯文物", traits: ["无聊", "有趣", "令人好奇的", "腹泻的幽默", "望而生畏"], description: "减少访客的娱乐度,提升访客的娱乐度,提供的知识额外+1,好笑的惊吓方式，轻微影响肠胃舒适度,可对犯罪行动产生震慑效果", source: "双点海 - 湿特兰蒂斯荒野", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "102", name: "潜水盔甲", category: "海洋", subcategory: "湿特兰蒂斯文物", traits: ["无聊", "有趣", "令人好奇的", "腹泻的幽默", "望而生畏"], description: "减少访客的娱乐度,提升访客的娱乐度,提供的知识额外+1,好笑的惊吓方式，轻微影响肠胃舒适度,可对犯罪行动产生震慑效果", source: "双点海 - 湿特兰蒂斯荒野", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "103", name: "珍珠之母", category: "海洋", subcategory: "湿特兰蒂斯文物", traits: ["无聊", "有趣", "令人好奇的", "腹泻的幽默", "望而生畏"], description: "减少访客的娱乐度,提升访客的娱乐度,提供的知识额外+1,好笑的惊吓方式，轻微影响肠胃舒适度,可对犯罪行动产生震慑效果", source: "双点海 - 湿特兰蒂斯墓穴", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "104", name: "湿特兰蒂斯餐具", category: "海洋", subcategory: "湿特兰蒂斯文物", traits: ["无聊", "有趣", "令人好奇的", "腹泻的幽默", "望而生畏"], description: "减少访客的娱乐度,提升访客的娱乐度,提供的知识额外+1,好笑的惊吓方式，轻微影响肠胃舒适度,可对犯罪行动产生震慑效果", source: "双点海 - 湿特兰蒂斯墓穴", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "105", name: "珊瑚头冠", category: "海洋", subcategory: "湿特兰蒂斯文物", traits: ["无聊", "有趣", "令人好奇的", "腹泻的幽默", "望而生畏"], description: "减少访客的娱乐度,提升访客的娱乐度,提供的知识额外+1,好笑的惊吓方式，轻微影响肠胃舒适度,可对犯罪行动产生震慑效果", source: "双点海 - 湿特兰蒂斯藏宝所", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "106", name: "热水气球", category: "海洋", subcategory: "湿特兰蒂斯文物", traits: ["无聊", "有趣", "令人好奇的", "腹泻的幽默", "望而生畏"], description: "减少访客的娱乐度,提升访客的娱乐度,提供的知识额外+1,好笑的惊吓方式，轻微影响肠胃舒适度,可对犯罪行动产生震慑效果", source: "双点海 - 湿特兰蒂斯上城区", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "107", name: "湿特兰蒂斯马赛克瓷砖", category: "海洋", subcategory: "湿特兰蒂斯文物", traits: ["无聊", "有趣", "令人好奇的", "腹泻的幽默", "望而生畏"], description: "减少访客的娱乐度,提升访客的娱乐度,提供的知识额外+1,好笑的惊吓方式，轻微影响肠胃舒适度,可对犯罪行动产生震慑效果", source: "双点海 - 湿特兰蒂斯中心区", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "108", name: "海洋水塞", category: "海洋", subcategory: "湿特兰蒂斯文物", traits: ["无聊", "有趣", "令人好奇的", "腹泻的幽默", "望而生畏"], description: "减少访客的娱乐度,提升访客的娱乐度,提供的知识额外+1,好笑的惊吓方式，轻微影响肠胃舒适度,可对犯罪行动产生震慑效果", source: "双点海 - 湿特兰蒂斯中心区", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  // --- 海洋 / 湿特兰蒂斯废墟 ---
  { id: "109", name: "大门废墟", category: "海洋", subcategory: "湿特兰蒂斯废墟", traits: ["无聊", "有趣", "令人好奇的", "腹泻的幽默", "望而生畏", "室外用品"], description: "减少访客的娱乐度,提升访客的娱乐度,提供的知识额外+1,好笑的惊吓方式，轻微影响肠胃舒适度,可对犯罪行动产生震慑效果,必须放在室外", source: "双点海 - 湿特兰蒂斯上城区", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "110", name: "集会所废墟", category: "海洋", subcategory: "湿特兰蒂斯废墟", traits: ["无聊", "有趣", "令人好奇的", "腹泻的幽默", "望而生畏", "室外用品"], description: "减少访客的娱乐度,提升访客的娱乐度,提供的知识额外+1,好笑的惊吓方式，轻微影响肠胃舒适度,可对犯罪行动产生震慑效果,必须放在室外", source: "双点海 - 湿特兰蒂斯上城区", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "111", name: "雕像废墟", category: "海洋", subcategory: "湿特兰蒂斯废墟", traits: ["无聊", "有趣", "令人好奇的", "腹泻的幽默", "望而生畏", "室外用品"], description: "减少访客的娱乐度,提升访客的娱乐度,提供的知识额外+1,好笑的惊吓方式，轻微影响肠胃舒适度,可对犯罪行动产生震慑效果,必须放在室外", source: "双点海 - 湿特兰蒂斯中心区", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "112", name: "珊瑚剧场废墟", category: "海洋", subcategory: "湿特兰蒂斯废墟", traits: ["无聊", "有趣", "令人好奇的", "腹泻的幽默", "望而生畏", "室外用品"], description: "减少访客的娱乐度,提升访客的娱乐度,提供的知识额外+1,好笑的惊吓方式，轻微影响肠胃舒适度,可对犯罪行动产生震慑效果,必须放在室外", source: "双点海 - 湿特兰蒂斯中心区", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  // --- 超自然 / 自然灵体 ---
  { id: "113", name: "穴居人", category: "超自然", subcategory: "自然灵体", traits: ["领袖", "收藏家", "洞穴喜剧人", "治疗师", "猎人"], description: "部落首领，每个房间仅可存在一名,非常喜欢家具,提升其他灵体的娱乐度,有几率治疗员工的伤病,有几率为访客提供食物与饮料", source: "冥界, 白骨带 - 凋零之路, 迷雾沼泽", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "114", name: "野人", category: "超自然", subcategory: "自然灵体", traits: ["作家", "高山急救师", "冰雕师", "高山歌手", "海洋野人", "才智超群", "四海为家", "野人名流"], description: "增加访客参观冰封珍品时获得的热议度,有几率会治疗员工的伤病,增加访客参观冰封珍品时获得的热议度,用自己的音乐天赋提升访客的娱乐度,非常喜欢大海（+3知识）,增加访客的知识（+2知识）,适应力极强，到哪都像自己家,高山首领，每个房间仅可存在一名", source: "冥界 - 寒冰尖塔", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "115", name: "呱星人", category: "超自然", subcategory: "自然灵体", traits: ["医护人员", "呱唱家", "星级游侠", "著名青蛙", "贤者", "驻外大使", "长老"], description: "有几率会治疗员工的伤病,用自己的音乐天赋提升访客的娱乐度,喜欢待在室内,驰名宇宙，增加访客参观太空展示品时获得的热议度,比其他灵体更平静,增加访客的参观时长,族群首领，每个房间仅可存在一名", source: "冥界 - 蘑菇荒原", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "116", name: "哥布林", category: "超自然", subcategory: "自然灵体", traits: ["开心果"], description: "提升其他灵体的娱乐度", source: "焦土世界 - 上古战场", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  // --- 超自然 / 著名灵体 ---
  { id: "117", name: "宾·西瓦臀", category: "超自然", subcategory: "著名灵体", traits: ["独一无二", "助理"], description: "世上仅此一个,提供最佳客户服务", source: "白骨带 - 凋零之路", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "118", name: "异次元时光队长", category: "超自然", subcategory: "著名灵体", traits: ["独一无二", "时间旅行者"], description: "世上仅此一个,唯一一个从隔壁次元来的人……", source: "冥界 - 异次元时光", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "119", name: "布奇·腌黄瓜斯", category: "超自然", subcategory: "著名灵体", traits: ["独一无二", "弗莱明顿球员"], description: "世上仅此一个,曾代表弗莱明顿打比赛的奶酪球选手", source: "冥界 - 默灵剧院", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "120", name: "赫丝特·鬼迪方", category: "超自然", subcategory: "著名灵体", traits: ["独一无二", "王牌双子星"], description: "世上仅此一个,让其他灵体的平静度降低得更快", source: "冥界 - 鬼迪方老巢", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "121", name: "汉弗莱·鬼迪方", category: "超自然", subcategory: "著名灵体", traits: ["独一无二", "王牌双子星"], description: "世上仅此一个,让其他灵体的平静度降低得更快", source: "冥界 - 逆向通道", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "122", name: "丹尼斯·布拉加德领主", category: "超自然", subcategory: "著名灵体", traits: ["独一无二", "布拉加德领主"], description: "世上仅此一个,让其他灵体的平静度降低得更慢，万岁", source: "冥界 - 半恶城堡", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "123", name: "崔吉·西瓦臀", category: "超自然", subcategory: "著名灵体", traits: ["独一无二", "专家"], description: "世上仅此一个,增加访客的参观时长", source: "冥界 - 安息之地", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "124", name: "阿特拉斯·斯皮芬多", category: "超自然", subcategory: "著名灵体", traits: ["独一无二", "伟大巫师"], description: "世上仅此一个,会诅咒或祝福员工", source: "冥界 - 斯皮芬多尖塔", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "125", name: "玛格丽特·菲茨普奇特", category: "超自然", subcategory: "著名灵体", traits: ["独一无二", "艺术家"], description: "世上仅此一个,爱用灵质进行极具创意力的创作", source: "冥界 - 沉眠庭院", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "126", name: "掠金船长", category: "超自然", subcategory: "著名灵体", traits: ["独一无二"], description: "世上仅此一个", source: "双点海 - S.S.西瓦臀号", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "127", name: "比什·西瓦臀", category: "超自然", subcategory: "著名灵体", traits: ["独一无二", "保安"], description: "世上仅此一个,让其他灵体的平静度降低得更慢", source: "双点海 - 西瓦臀打捞点", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "128", name: "毕夫·西瓦臀", category: "超自然", subcategory: "著名灵体", traits: ["独一无二"], description: "世上仅此一个", source: "低端科技地穴 - 低温实验室", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  // --- 超自然 / 工业时代灵体 ---
  { id: "129", name: "鬼迪方爪牙", category: "超自然", subcategory: "工业时代灵体", traits: ["小头领", "保镖", "打手", "扒手", "勤杂工"], description: "让鬼迪方灵体的平静度降低得更慢。让其他灵体的平静度降低得更快,喜欢待在室内,头脑简单，四肢发达，只会动粗,有几率会掉落食物给员工,会清理其他人留下的垃圾", source: "冥界 - 逆向通道, 鬼迪方老巢", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "130", name: "维多利亚时代名流", category: "超自然", subcategory: "工业时代灵体", traits: ["作曲家", "室内设计师", "艺术家", "学者", "医生", "图书管理员", "喜剧人", "哲学家", "历史学家"], description: "用自己的音乐天赋提升访客的娱乐度,非常喜欢家具,爱用灵质进行极具创意力的创作,提供更多知识,有几率会治疗员工的伤病,从虫子吃人的时代起已经是书虫了,提升其他灵体的娱乐度,比其他灵体更平静,非常喜欢黑暗时代", source: "冥界 - 超自然观测机构", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "131", name: "难头症患者", category: "超自然", subcategory: "工业时代灵体", traits: ["作曲家", "室内设计师", "艺术家", "学者", "医生", "图书管理员", "喜剧人", "哲学家", "历史学家"], description: "用自己的音乐天赋提升访客的娱乐度,非常喜欢家具,爱用灵质进行极具创意力的创作,提供更多知识,有几率会治疗员工的伤病,从虫子吃人的时代起已经是书虫了,提升其他灵体的娱乐度,比其他灵体更平静,非常喜欢黑暗时代", source: "冥界 - 默灵剧院", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "132", name: "维多利亚时代平民", category: "超自然", subcategory: "工业时代灵体", traits: ["吟游诗人", "烟囱清洁工", "园艺师", "酒店员工", "流浪汉", "马戏团演员", "厨师"], description: "用自己的音乐天赋提升访客的娱乐度,灰头土脸，风尘仆仆,非常热爱大自然,非常喜欢酒店,喜欢待在室内,提升其他灵体的娱乐度,有几率会掉落食物给员工", source: "冥界 - 无尽垃圾场", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "133", name: "传奇奶酪球选手", category: "超自然", subcategory: "工业时代灵体", traits: ["弗莱明顿球员", "烟熏镇球员", "霍格思波特球员"], description: "曾代表弗莱明顿打比赛的奶酪球选手,共处一室的其他灵体少于两个时，平静度降低得更快,曾代表霍格思波特打比赛的奶酪球选手", source: "冥界 - 冥界展会", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  // --- 超自然 / 黑暗时代灵体 ---
  { id: "134", name: "庶民", category: "超自然", subcategory: "黑暗时代灵体", traits: ["佣人", "骑士侍从", "小丑", "隐士", "铁匠"], description: "会清理其他人留下的垃圾,骑士的最佳好友,提升其他灵体的娱乐度,喜欢待在室内,叮叮哐哐", source: "冥界 - 死神农园", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "135", name: "骑士", category: "超自然", subcategory: "黑暗时代灵体", traits: ["布拉加德骑士", "无赖骑士", "诺伯斯泰德骑士"], description: "布拉加德骑士团的一员,自诩为骑士团的一员,诺伯斯泰德骑士团的一员", source: "冥界 - 半恶城堡", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  // --- 超自然 / 著名藏品 ---
  { id: "136", name: "腌黄瓜斯的刨丝器", category: "超自然", subcategory: "著名藏品", traits: ["独一无二"], description: "世上仅此一个", source: "冥界 - 默灵剧院", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "137", name: "鬼迪方保险柜", category: "超自然", subcategory: "著名藏品", traits: ["独一无二"], description: "世上仅此一个", source: "冥界 - 鬼迪方老巢", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "138", name: "鬼迪方椅子", category: "超自然", subcategory: "著名藏品", traits: ["独一无二"], description: "世上仅此一个", source: "冥界 - 逆向通道", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "139", name: "布拉加德之剑", category: "超自然", subcategory: "著名藏品", traits: ["独一无二"], description: "世上仅此一个", source: "冥界 - 半恶城堡", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "140", name: "斯皮芬多的帽子", category: "超自然", subcategory: "著名藏品", traits: ["独一无二"], description: "世上仅此一个", source: "冥界 - 斯皮芬多尖塔", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "141", name: "菲茨普奇特画架", category: "超自然", subcategory: "著名藏品", traits: ["独一无二"], description: "世上仅此一个", source: "冥界 - 沉眠庭院", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  // --- 超自然 / 除鬼设备 ---
  { id: "142", name: "驱鬼动力装置", category: "超自然", subcategory: "除鬼设备", traits: ["无"], description: "", source: "冥界 - 安息之地", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "143", name: "驱鬼机", category: "超自然", subcategory: "除鬼设备", traits: ["无"], description: "", source: "冥界 - 超自然观测机构", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "144", name: "除鬼器1.0版", category: "超自然", subcategory: "除鬼设备", traits: ["无"], description: "", source: "冥界 - 超自然观测机构", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "145", name: "捕鬼网", category: "超自然", subcategory: "除鬼设备", traits: ["无"], description: "", source: "冥界 - 迷雾沼泽", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "146", name: "捉鬼风箱", category: "超自然", subcategory: "除鬼设备", traits: ["无"], description: "", source: "冥界 - 沉眠庭院", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  // --- 超自然 / 诅咒物品 ---
  { id: "147", name: "闹鬼的马匹", category: "超自然", subcategory: "诅咒物品", traits: ["鬼魅诱惑", "恶灵修复", "厕所跳脸杀", "永恒沉眠", "混沌之雨"], description: "恐怖与迷人的完美平衡，令人欲罢不能（提升娱乐度+5%）,被躁动不安的灵体附身，灵体会一直为其宿主进行清洁，清洁度会逐渐恢复至100%,最糟糕的惊吓方式，严重影响肠胃舒适度（-10%）,让人陷入深度睡眠，能量将会减少（-5%）,邪恶之力让博物馆充满垃圾，会导致访客无视垃圾桶，随地乱扔垃圾", source: "冥界 - 死神农园", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "148", name: "闹鬼的盔甲", category: "超自然", subcategory: "诅咒物品", traits: ["鬼魅诱惑", "恶灵修复", "厕所跳脸杀", "永恒沉眠", "混沌之雨"], description: "恐怖与迷人的完美平衡，令人欲罢不能（提升娱乐度+5%）,被躁动不安的灵体附身，灵体会一直为其宿主进行清洁，清洁度会逐渐恢复至100%,最糟糕的惊吓方式，严重影响肠胃舒适度（-10%）,让人陷入深度睡眠，能量将会减少（-5%）,邪恶之力让博物馆充满垃圾，会导致访客无视垃圾桶，随地乱扔垃圾", source: "冥界 - 半恶城堡", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "149", name: "闹鬼的厕所", category: "超自然", subcategory: "诅咒物品", traits: ["鬼魅诱惑", "恶灵修复", "厕所跳脸杀", "永恒沉眠", "混沌之雨"], description: "恐怖与迷人的完美平衡，令人欲罢不能（提升娱乐度+5%）,被躁动不安的灵体附身，灵体会一直为其宿主进行清洁，清洁度会逐渐恢复至100%,最糟糕的惊吓方式，严重影响肠胃舒适度（-10%）,让人陷入深度睡眠，能量将会减少（-5%）,邪恶之力让博物馆充满垃圾，会导致访客无视垃圾桶，随地乱扔垃圾", source: "冥界 - 深谙瀑布", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "150", name: "羞怯半身像", category: "超自然", subcategory: "诅咒物品", traits: ["鬼魅诱惑", "恶灵修复", "厕所跳脸杀", "永恒沉眠", "混沌之雨"], description: "恐怖与迷人的完美平衡，令人欲罢不能（提升娱乐度+5%）,被躁动不安的灵体附身，灵体会一直为其宿主进行清洁，清洁度会逐渐恢复至100%,最糟糕的惊吓方式，严重影响肠胃舒适度（-10%）,让人陷入深度睡眠，能量将会减少（-5%）,邪恶之力让博物馆充满垃圾，会导致访客无视垃圾桶，随地乱扔垃圾", source: "冥界 - 安息之地", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "151", name: "小帮手", category: "超自然", subcategory: "诅咒物品", traits: ["鬼魅诱惑", "恶灵修复", "厕所跳脸杀", "永恒沉眠", "混沌之雨"], description: "恐怖与迷人的完美平衡，令人欲罢不能（提升娱乐度+5%）,被躁动不安的灵体附身，灵体会一直为其宿主进行清洁，清洁度会逐渐恢复至100%,最糟糕的惊吓方式，严重影响肠胃舒适度（-10%）,让人陷入深度睡眠，能量将会减少（-5%）,邪恶之力让博物馆充满垃圾，会导致访客无视垃圾桶，随地乱扔垃圾", source: "冥界 - 斯皮芬多尖塔", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "152", name: "被占的椅子", category: "超自然", subcategory: "诅咒物品", traits: ["鬼魅诱惑", "恶灵修复", "厕所跳脸杀", "永恒沉眠", "混沌之雨"], description: "恐怖与迷人的完美平衡，令人欲罢不能（提升娱乐度+5%）,被躁动不安的灵体附身，灵体会一直为其宿主进行清洁，清洁度会逐渐恢复至100%,最糟糕的惊吓方式，严重影响肠胃舒适度（-10%）,让人陷入深度睡眠，能量将会减少（-5%）,邪恶之力让博物馆充满垃圾，会导致访客无视垃圾桶，随地乱扔垃圾", source: "冥界 - 斯皮芬多尖塔", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "153", name: "闹鬼的电视", category: "超自然", subcategory: "诅咒物品", traits: ["鬼魅诱惑", "恶灵修复", "厕所跳脸杀", "永恒沉眠", "混沌之雨"], description: "恐怖与迷人的完美平衡，令人欲罢不能（提升娱乐度+5%）,被躁动不安的灵体附身，灵体会一直为其宿主进行清洁，清洁度会逐渐恢复至100%,最糟糕的惊吓方式，严重影响肠胃舒适度（-10%）,让人陷入深度睡眠，能量将会减少（-5%）,邪恶之力让博物馆充满垃圾，会导致访客无视垃圾桶，随地乱扔垃圾", source: "冥界 - 默灵剧院", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "154", name: "罗奇汉堡角色展示台", category: "超自然", subcategory: "诅咒物品", traits: ["恶灵修复", "鬼魅诱惑", "厕所跳脸杀", "永恒沉眠", "混沌之雨"], description: "被躁动不安的灵体附身，灵体会一直为其宿主进行清洁，清洁度会逐渐恢复至100%,恐怖与迷人的完美平衡，令人欲罢不能（提升娱乐度+5%）,最糟糕的惊吓方式，严重影响肠胃舒适度（-10%）,让人陷入深度睡眠，能量将会减少（-5%）,邪恶之力让博物馆充满垃圾，会导致访客无视垃圾桶，随地乱扔垃圾", source: "冥界 - 无尽垃圾场", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "155", name: "闹鬼的床铺", category: "超自然", subcategory: "诅咒物品", traits: ["厕所跳脸杀", "鬼魅诱惑", "恶灵修复", "永恒沉眠", "混沌之雨"], description: "最糟糕的惊吓方式，严重影响肠胃舒适度（-10%）,恐怖与迷人的完美平衡，令人欲罢不能（提升娱乐度+5%）,被躁动不安的灵体附身，灵体会一直为其宿主进行清洁，清洁度会逐渐恢复至100%,让人陷入深度睡眠，能量将会减少（-5%）,邪恶之力让博物馆充满垃圾，会导致访客无视垃圾桶，随地乱扔垃圾", source: "冥界 - 寒冰尖塔", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "156", name: "闹鬼的肖像画", category: "超自然", subcategory: "诅咒物品", traits: ["鬼魅诱惑", "恶灵修复", "厕所跳脸杀", "永恒沉眠", "混沌之雨"], description: "恐怖与迷人的完美平衡，令人欲罢不能（提升娱乐度+5%）,被躁动不安的灵体附身，灵体会一直为其宿主进行清洁，清洁度会逐渐恢复至100%,最糟糕的惊吓方式，严重影响肠胃舒适度（-10%）,让人陷入深度睡眠，能量将会减少（-5%）,邪恶之力让博物馆充满垃圾，会导致访客无视垃圾桶，随地乱扔垃圾", source: "冥界 - 沉眠庭院", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "157", name: "闹鬼的惊吓盒", category: "超自然", subcategory: "诅咒物品", traits: ["鬼魅诱惑", "恶灵修复", "厕所跳脸杀", "永恒沉眠", "混沌之雨"], description: "恐怖与迷人的完美平衡，令人欲罢不能（提升娱乐度+5%）,被躁动不安的灵体附身，灵体会一直为其宿主进行清洁，清洁度会逐渐恢复至100%,最糟糕的惊吓方式，严重影响肠胃舒适度（-10%）,让人陷入深度睡眠，能量将会减少（-5%）,邪恶之力让博物馆充满垃圾，会导致访客无视垃圾桶，随地乱扔垃圾", source: "冥界 - 冥界展会", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "158", name: "故障电话", category: "超自然", subcategory: "诅咒物品", traits: ["鬼魅诱惑", "恶灵修复", "厕所跳脸杀", "永恒沉眠", "混沌之雨"], description: "恐怖与迷人的完美平衡，令人欲罢不能（提升娱乐度+5%）,被躁动不安的灵体附身，灵体会一直为其宿主进行清洁，清洁度会逐渐恢复至100%,最糟糕的惊吓方式，严重影响肠胃舒适度（-10%）,让人陷入深度睡眠，能量将会减少（-5%）,邪恶之力让博物馆充满垃圾，会导致访客无视垃圾桶，随地乱扔垃圾", source: "冥界 - 炼狱车站", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "159", name: "闹鬼的娃娃", category: "超自然", subcategory: "诅咒物品", traits: ["鬼魅诱惑", "恶灵修复", "厕所跳脸杀", "永恒沉眠", "混沌之雨"], description: "恐怖与迷人的完美平衡，令人欲罢不能（提升娱乐度+5%）,被躁动不安的灵体附身，灵体会一直为其宿主进行清洁，清洁度会逐渐恢复至100%,最糟糕的惊吓方式，严重影响肠胃舒适度（-10%）,让人陷入深度睡眠，能量将会减少（-5%）,邪恶之力让博物馆充满垃圾，会导致访客无视垃圾桶，随地乱扔垃圾", source: "冥界 - 炼狱车站", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "160", name: "闹鬼的人体模型", category: "超自然", subcategory: "诅咒物品", traits: ["鬼魅诱惑", "恶灵修复", "厕所跳脸杀", "永恒沉眠", "混沌之雨"], description: "恐怖与迷人的完美平衡，令人欲罢不能（提升娱乐度+5%）,被躁动不安的灵体附身，灵体会一直为其宿主进行清洁，清洁度会逐渐恢复至100%,最糟糕的惊吓方式，严重影响肠胃舒适度（-10%）,让人陷入深度睡眠，能量将会减少（-5%）,邪恶之力让博物馆充满垃圾，会导致访客无视垃圾桶，随地乱扔垃圾", source: "冥界 - 炼狱车站", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  // --- 超自然 / 海滩灵体 ---
  { id: "161", name: "海盗", category: "超自然", subcategory: "海滩灵体", traits: ["海上清洁员", "大副", "船长", "炮手", "捕鱼师", "民谣歌手", "船上厨师", "船医"], description: "会清理其他人留下的垃圾,船长的左膀右臂,船舰首领，每个房间仅可存在一名,说话大声，像是吃了枪药,增加访客参观鱼类展示品时获得的热议度,用自己的音乐天赋提升访客的娱乐度,有几率会掉落食物给员工,有几率会治疗员工的伤病", source: "冥界, 双点海 - S.S.西瓦臀号, 深谙瀑布", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  // --- 超自然 / 神器 ---
  { id: "162", name: "巫术异典", category: "超自然", subcategory: "神器", traits: [], description: "", source: "数码宇宙 - 锦钿书库", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "163", name: "福音书", category: "超自然", subcategory: "神器", traits: [], description: "", source: "数码宇宙 - 大教堂", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "164", name: "邪恶秘典", category: "超自然", subcategory: "神器", traits: [], description: "", source: "数码宇宙 - 锦钿书库", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "165", name: "棺材", category: "超自然", subcategory: "神器", traits: [], description: "", source: "数码宇宙 - 大教堂", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  // --- 科学 / 插件 ---
  { id: "166", name: "大量知识加成", category: "科学", subcategory: "插件", traits: ["无"], description: "", source: "冥界 - 恶念地牢", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "167", name: "鬼灵套索", category: "科学", subcategory: "插件", traits: ["无"], description: "", source: "冥界 - 恶念地牢", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "168", name: "高度警惕", category: "科学", subcategory: "插件", traits: ["无"], description: "", source: "冥界 - 恶念地牢", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "169", name: "大范围监控", category: "科学", subcategory: "插件", traits: ["无"], description: "", source: "冥界 - 恶念地牢", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "170", name: "肥沃土壤", category: "科学", subcategory: "插件", traits: ["无"], description: "", source: "低端科技地穴 - 医学实验室", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "171", name: "热议度与参观时长加成", category: "科学", subcategory: "插件", traits: ["无"], description: "", source: "低端科技地穴 - 记忆实验室", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "172", name: "知识加成", category: "科学", subcategory: "插件", traits: ["无"], description: "", source: "低端科技地穴 - 电击实验室", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "173", name: "节电模式", category: "科学", subcategory: "插件", traits: ["无"], description: "", source: "低端科技地穴 - 充电实验室, 机器人实验室", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "174", name: "参观时长加成", category: "科学", subcategory: "插件", traits: ["无"], description: "", source: "低端科技地穴 - 化学实验室", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "175", name: "能量加成", category: "科学", subcategory: "插件", traits: ["无"], description: "", source: "低端科技地穴 - 化学实验室, 医学实验室, 迷你星人环形赛道", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "176", name: "限定版", category: "科学", subcategory: "插件", traits: ["无"], description: "", source: "低端科技地穴 - 充电实验室, 安全实验室, 激光实验室", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "177", name: "装饰与娱乐度加成", category: "科学", subcategory: "插件", traits: ["无"], description: "", source: "低端科技地穴 - 激光实验室", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "178", name: "装饰加成", category: "科学", subcategory: "插件", traits: ["无"], description: "", source: "低端科技地穴 - 激光实验室", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "179", name: "内置扬声器", category: "科学", subcategory: "插件", traits: ["无"], description: "", source: "低端科技地穴 - 低端科技地穴, 安全实验室", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "180", name: "简易设计", category: "科学", subcategory: "插件", traits: ["无"], description: "", source: "低端科技地穴 - 电击实验室", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "181", name: "快速充电", category: "科学", subcategory: "插件", traits: ["无"], description: "", source: "低端科技地穴 - 反情报实验室", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "182", name: "娱乐加成", category: "科学", subcategory: "插件", traits: ["无"], description: "", source: "低端科技地穴 - 化学实验室", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "183", name: "低廉电费", category: "科学", subcategory: "插件", traits: ["无"], description: "", source: "低端科技地穴 - 改装实验室, 机器人实验室", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "184", name: "铬合金镀层", category: "科学", subcategory: "插件", traits: ["无"], description: "", source: "低端科技地穴 - 反情报实验室, 改装实验室", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "185", name: "防锈", category: "科学", subcategory: "插件", traits: ["无"], description: "", source: "低端科技地穴 - 低端科技地穴, 充电实验室, 安全实验室", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "186", name: "热议度加成", category: "科学", subcategory: "插件", traits: ["无"], description: "", source: "低端科技地穴, 已知宇宙 - 低端科技地穴, 迷你星人环形赛道", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "187", name: "热议度与娱乐加成", category: "科学", subcategory: "插件", traits: ["无"], description: "", source: "已知宇宙 - 迷你星人环形赛道", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "188", name: "热议度与能量加成", category: "科学", subcategory: "插件", traits: ["无"], description: "", source: "已知宇宙 - 迷你星人环形赛道", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  // --- 科学 / 科研材料 ---
  { id: "189", name: "转轮", category: "科学", subcategory: "科研材料", traits: ["无"], description: "", source: "低端科技地穴 - 盈余物资储藏所", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "190", name: "水晶苔藓", category: "科学", subcategory: "科研材料", traits: ["无"], description: "", source: "低端科技地穴 - 水晶洞穴", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "191", name: "金松露", category: "科学", subcategory: "科研材料", traits: ["无"], description: "", source: "低端科技地穴 - 黄金矿坑", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "192", name: "金属", category: "科学", subcategory: "科研材料", traits: ["无"], description: "", source: "低端科技地穴 - 怪石采石场", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  // --- 科学 / 古典装置 ---
  { id: "193", name: "注射宗师", category: "科学", subcategory: "古典装置", traits: ["无"], description: "", source: "低端科技地穴 - 上层古董档案馆", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "194", name: "飞行器", category: "科学", subcategory: "古典装置", traits: ["无"], description: "", source: "低端科技地穴 - 上层古董档案馆", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "195", name: "火车头", category: "科学", subcategory: "古典装置", traits: ["无"], description: "", source: "低端科技地穴 - 下层古董档案馆", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "196", name: "绷带筐", category: "科学", subcategory: "古典装置", traits: ["无"], description: "", source: "低端科技地穴 - 下层古董档案馆", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "197", name: "印刷机", category: "科学", subcategory: "古典装置", traits: ["无"], description: "", source: "低端科技地穴 - 下层古董档案馆", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  // --- 科学 / 定制装置 ---
  { id: "198", name: "堆肥生产机", category: "科学", subcategory: "定制装置", traits: ["堆肥生产机"], description: "可将植物展示品转化为堆肥", source: "低端科技地穴", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "199", name: "药浴治疗机", category: "科学", subcategory: "定制装置", traits: ["药浴治疗机"], description: "治疗员工的疾病和伤病", source: "低端科技地穴 - 医学实验室", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "200", name: "机器人充电装置", category: "科学", subcategory: "定制装置", traits: ["机器人充电装置"], description: "可为机器人员工补充能量，充电成本十分低廉", source: "低端科技地穴", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "201", name: "DNA设计器", category: "科学", subcategory: "定制装置", traits: ["DNA设计器"], description: "可将访客转变为特定的原型", source: "低端科技地穴", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "202", name: "记忆数据库蓝图", category: "科学", subcategory: "定制装置", traits: ["记忆数据库"], description: "给员工上传常年积累下来的XP", source: "低端科技地穴 - 电击实验室, 记忆实验室", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "203", name: "美化激光装置蓝图", category: "科学", subcategory: "定制装置", traits: ["美化激光装置"], description: "参观该展示品的访客可获得环境值加成", source: "低端科技地穴 - 激光实验室", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "204", name: "全方位监测塔蓝图", category: "科学", subcategory: "定制装置", traits: ["全方位监测塔"], description: "有一定概率辨别出伪装的罪犯", source: "低端科技地穴 - 安全实验室", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "205", name: "震能转换器蓝图", category: "科学", subcategory: "定制装置", traits: ["震能转换器"], description: "为附近的访客提升少量移动速度", source: "低端科技地穴 - 记忆实验室, 电击实验室", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "206", name: "空气指挥器蓝图", category: "科学", subcategory: "定制装置", traits: ["空气指挥器"], description: "控制周围的温度", source: "低端科技地穴 - 低温实验室", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "207", name: "机器保安蓝图", category: "科学", subcategory: "定制装置", traits: [], description: "", source: "低端科技地穴 - 反情报实验室", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "208", name: "机器人充电大师蓝图", category: "科学", subcategory: "定制装置", traits: ["机器人充电大师"], description: "可为机器人员工补充能量，充电成本十分低廉", source: "低端科技地穴 - 充电实验室", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "209", name: "雾判机蓝图", category: "科学", subcategory: "定制装置", traits: ["雾判机"], description: "使用定制的化学物质对访客的参观体验带来一些影响", source: "低端科技地穴 - 化学实验室", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "210", name: "机器勤杂工蓝图", category: "科学", subcategory: "定制装置", traits: [], description: "", source: "低端科技地穴 - 机器人实验室", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "211", name: "机器人改造站蓝图", category: "科学", subcategory: "定制装置", traits: ["机器人改造站"], description: "可对机器人员工进行改造，使其根据需求为用户提供个性化帮助", source: "低端科技地穴 - 改装实验室", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "212", name: "洒水泵蓝图", category: "科学", subcategory: "定制装置", traits: ["洒水泵"], description: "浇灌（修复）附近的植物展示品", source: "低端科技地穴", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "213", name: "SPA休息站", category: "科学", subcategory: "定制装置", traits: ["SPA休息站"], description: "参观该展示品的访客可获得能量加成", source: "其他", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  // --- 太空 / 星界异象 ---
  { id: "214", name: "异象：太空球", category: "太空", subcategory: "星界异象", traits: ["星际异象", "太空智慧", "有趣", "令人好奇的", "望而生畏"], description: "这件展示品上的神秘符号绝对十分关键,提供更多知识,提升访客的娱乐度,提供的知识额外+1,可对犯罪行动产生震慑效果", source: "已知宇宙 - 奶酪主舰", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "215", name: "异象：轨道图腾", category: "太空", subcategory: "星界异象", traits: ["疗愈之声", "星际异象", "有趣", "令人好奇的", "望而生畏"], description: "提升幸福感,这件展示品上的神秘符号绝对十分关键,提升访客的娱乐度,提供的知识额外+1,可对犯罪行动产生震慑效果", source: "已知宇宙 - 蓝酪月球", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "216", name: "异象：“谜题之塔”", category: "太空", subcategory: "星界异象", traits: ["星际异象", "太空赠礼", "有趣", "令人好奇的", "望而生畏"], description: "这件展示品上的神秘符号绝对十分关键,提升热议度、知识和幸福感,提升访客的娱乐度,提供的知识额外+1,可对犯罪行动产生震慑效果", source: "已知宇宙 - 异象档案馆", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "217", name: "异象：“痛苦之台”", category: "太空", subcategory: "星界异象", traits: ["星际大门", "星际异象", "有趣", "令人好奇的", "望而生畏"], description: "提升幸福感,这件展示品上的神秘符号绝对十分关键,提升访客的娱乐度,提供的知识额外+1,可对犯罪行动产生震慑效果", source: "已知宇宙 - 异象档案馆", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "218", name: "异象：“搅拌装置”", category: "太空", subcategory: "星界异象", traits: ["太空榨汁机", "星际异象", "有趣", "令人好奇的", "望而生畏"], description: "增加吃饱度和喝饱度,这件展示品上的神秘符号绝对十分关键,提升访客的娱乐度,提供的知识额外+1,可对犯罪行动产生震慑效果", source: "已知宇宙 - 迷你月球一号", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "219", name: "异象：“压力舱”", category: "太空", subcategory: "星界异象", traits: ["太空厕所", "星际异象", "有趣", "令人好奇的", "望而生畏"], description: "持续提升肠胃舒适度,这件展示品上的神秘符号绝对十分关键,提升访客的娱乐度,提供的知识额外+1,可对犯罪行动产生震慑效果", source: "已知宇宙 - 迷你月球二号", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "220", name: "异象：“月球废物”", category: "太空", subcategory: "星界异象", traits: ["太空椅", "星际异象", "有趣", "令人好奇的", "望而生畏"], description: "提升能量,这件展示品上的神秘符号绝对十分关键,提升访客的娱乐度,提供的知识额外+1,可对犯罪行动产生震慑效果", source: "已知宇宙 - 迷你月球三号", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "221", name: "异象：“弹道触须”", category: "太空", subcategory: "星界异象", traits: ["太空之拥", "星际异象", "有趣", "令人好奇的", "望而生畏"], description: "提升娱乐度,这件展示品上的神秘符号绝对十分关键,提升访客的娱乐度,提供的知识额外+1,可对犯罪行动产生震慑效果", source: "已知宇宙 - 星莲平台", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "222", name: "异象：“星辰刺蜂”", category: "太空", subcategory: "星界异象", traits: ["太空蜜蜂", "星际异象", "有趣", "令人好奇的", "望而生畏"], description: "增加热议度,这件展示品上的神秘符号绝对十分关键,提升访客的娱乐度,提供的知识额外+1,可对犯罪行动产生震慑效果", source: "已知宇宙 - 超速航路服务区", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "223", name: "异象：“坠落平台”", category: "太空", subcategory: "星界异象", traits: ["太空池塘", "星际异象", "有趣", "令人好奇的", "望而生畏"], description: "提升移动速度,这件展示品上的神秘符号绝对十分关键,提升访客的娱乐度,提供的知识额外+1,可对犯罪行动产生震慑效果", source: "已知宇宙 - 海莉的彗星", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "224", name: "异象：“星光炮”", category: "太空", subcategory: "星界异象", traits: ["宇宙级市场营销", "星际异象", "有趣", "令人好奇的", "望而生畏"], description: "提升访客的留馆意愿,这件展示品上的神秘符号绝对十分关键,提升访客的娱乐度,提供的知识额外+1,可对犯罪行动产生震慑效果", source: "已知宇宙 - 海莉的彗星", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "225", name: "异象：宇宙之桌", category: "太空", subcategory: "星界异象", traits: ["宇宙制造", "星际异象", "有趣", "令人好奇的", "望而生畏"], description: "可生成装饰物品,这件展示品上的神秘符号绝对十分关键,提升访客的娱乐度,提供的知识额外+1,可对犯罪行动产生震慑效果", source: "已知宇宙 - 月球", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "226", name: "方形天体电池", category: "太空", subcategory: "星界异象", traits: ["星际异象", "有趣", "令人好奇的", "望而生畏"], description: "这件展示品上的神秘符号绝对十分关键,提升访客的娱乐度,提供的知识额外+1,可对犯罪行动产生震慑效果", source: "已知宇宙 - 月球", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "227", name: "异象：银河球茎", category: "太空", subcategory: "星界异象", traits: ["太空之花", "星际异象", "有趣", "令人好奇的", "望而生畏"], description: "防止访客的环境值下降,这件展示品上的神秘符号绝对十分关键,提升访客的娱乐度,提供的知识额外+1,可对犯罪行动产生震慑效果", source: "已知宇宙 - 双点轨道", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "228", name: "圆形天体电池", category: "太空", subcategory: "星界异象", traits: ["星际异象", "有趣", "令人好奇的", "望而生畏"], description: "这件展示品上的神秘符号绝对十分关键,提升访客的娱乐度,提供的知识额外+1,可对犯罪行动产生震慑效果", source: "已知宇宙 - 双点轨道", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "229", name: "三角天体电池", category: "太空", subcategory: "星界异象", traits: ["星际异象", "有趣", "令人好奇的", "望而生畏"], description: "这件展示品上的神秘符号绝对十分关键,提升访客的娱乐度,提供的知识额外+1,可对犯罪行动产生震慑效果", source: "已知宇宙 - 双点轨道", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  // --- 太空 / 奶酪月球人文物 ---
  { id: "230", name: "奶酪自由轮", category: "太空", subcategory: "奶酪月球人文物", traits: ["望而生畏", "令人好奇的", "有趣"], description: "可对犯罪行动产生震慑效果,提供的知识额外+1,提升访客的娱乐度", source: "已知宇宙 - 奶酪主舰", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "231", name: "奶酪切削机", category: "太空", subcategory: "奶酪月球人文物", traits: ["望而生畏", "令人好奇的", "有趣"], description: "可对犯罪行动产生震慑效果,提供的知识额外+1,提升访客的娱乐度", source: "已知宇宙 - 奶酪主舰", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "232", name: "奶酪精炼器", category: "太空", subcategory: "奶酪月球人文物", traits: ["望而生畏", "令人好奇的", "有趣"], description: "可对犯罪行动产生震慑效果,提供的知识额外+1,提升访客的娱乐度", source: "已知宇宙 - 马斯苏特拉星", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "233", name: "奶酪冲压机", category: "太空", subcategory: "奶酪月球人文物", traits: ["望而生畏", "令人好奇的", "有趣"], description: "可对犯罪行动产生震慑效果,提供的知识额外+1,提升访客的娱乐度", source: "已知宇宙 - 马斯苏特拉星", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "234", name: "蛞蝓雕像", category: "太空", subcategory: "奶酪月球人文物", traits: ["望而生畏", "令人好奇的", "有趣", "蛞蝓优选"], description: "可对犯罪行动产生震慑效果,提供的知识额外+1,提升访客的娱乐度,提升少量吃饱度", source: "已知宇宙 - 马斯苏特拉星", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  // --- 太空 / 蛙灵古物 ---
  { id: "235", name: "呱星人法老", category: "太空", subcategory: "蛙灵古物", traits: ["望而生畏", "令人好奇的", "有趣"], description: "可对犯罪行动产生震慑效果,提供的知识额外+1,提升访客的娱乐度", source: "已知宇宙 - 呱星尼亚", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "236", name: "呱星人育婴池", category: "太空", subcategory: "蛙灵古物", traits: ["望而生畏", "令人好奇的", "有趣"], description: "可对犯罪行动产生震慑效果,提供的知识额外+1,提升访客的娱乐度", source: "已知宇宙 - 呱星尼亚", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "237", name: "呱特拉斯巨像", category: "太空", subcategory: "蛙灵古物", traits: ["望而生畏", "令人好奇的", "有趣"], description: "可对犯罪行动产生震慑效果,提供的知识额外+1,提升访客的娱乐度", source: "已知宇宙 - 呱星尼亚", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "238", name: "呱呱快艇", category: "太空", subcategory: "蛙灵古物", traits: ["望而生畏", "令人好奇的", "有趣"], description: "可对犯罪行动产生震慑效果,提供的知识额外+1,提升访客的娱乐度", source: "已知宇宙 - 星莲平台", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "239", name: "苍蝇冰淇淋机", category: "太空", subcategory: "蛙灵古物", traits: ["望而生畏", "令人好奇的", "有趣"], description: "可对犯罪行动产生震慑效果,提供的知识额外+1,提升访客的娱乐度", source: "已知宇宙 - 超速航路服务区", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  // --- 太空 / 迷你星人 ---
  { id: "240", name: "太空割草机", category: "太空", subcategory: "迷你星人", traits: ["望而生畏", "令人好奇的", "有趣"], description: "可对犯罪行动产生震慑效果,提供的知识额外+1,提升访客的娱乐度", source: "已知宇宙 - 迷你月球一号", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "241", name: "太空车床", category: "太空", subcategory: "迷你星人", traits: ["望而生畏", "令人好奇的", "有趣"], description: "可对犯罪行动产生震慑效果,提供的知识额外+1,提升访客的娱乐度", source: "已知宇宙 - 迷你月球一号", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "242", name: "太空摩托", category: "太空", subcategory: "迷你星人", traits: ["望而生畏", "令人好奇的", "有趣"], description: "可对犯罪行动产生震慑效果,提供的知识额外+1,提升访客的娱乐度", source: "已知宇宙 - 迷你月球二号", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "243", name: "太空传送装置", category: "太空", subcategory: "迷你星人", traits: ["望而生畏", "令人好奇的", "有趣"], description: "可对犯罪行动产生震慑效果,提供的知识额外+1,提升访客的娱乐度", source: "已知宇宙 - 迷你月球二号", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "244", name: "瓶中太空飞船", category: "太空", subcategory: "迷你星人", traits: ["望而生畏", "令人好奇的", "有趣"], description: "可对犯罪行动产生震慑效果,提供的知识额外+1,提升访客的娱乐度", source: "已知宇宙 - 迷你月球三号", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  // --- 太空 / 太空垃圾 ---
  { id: "245", name: "月球靴", category: "太空", subcategory: "太空垃圾", traits: ["望而生畏", "令人好奇的", "有趣"], description: "可对犯罪行动产生震慑效果,提供的知识额外+1,提升访客的娱乐度", source: "已知宇宙 - 蓝酪月球", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "246", name: "卫星", category: "太空", subcategory: "太空垃圾", traits: ["望而生畏", "令人好奇的", "有趣"], description: "可对犯罪行动产生震慑效果,提供的知识额外+1,提升访客的娱乐度", source: "已知宇宙 - 超速航路服务区", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "247", name: "悬浮的太空陨石", category: "太空", subcategory: "太空垃圾", traits: ["望而生畏", "令人好奇的", "有趣"], description: "可对犯罪行动产生震慑效果,提供的知识额外+1,提升访客的娱乐度", source: "已知宇宙 - 月球, 海莉的彗星", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  // --- 奇幻 / 魔法珍品 ---
  { id: "248", name: "双面硬币", category: "奇幻", subcategory: "魔法珍品", traits: [], description: "", source: "焦土世界 - 传诵镇", base_buzz: 22, max_buzz: 114, max_knowledge: 0 },
  { id: "249", name: "飞毯", category: "奇幻", subcategory: "魔法珍品", traits: ["魔幻飞旅"], description: "", source: "焦土世界 - 幻境集市", base_buzz: 22, max_buzz: 114, max_knowledge: 0 },
  { id: "250", name: "黃金哥布林雕像", category: "奇幻", subcategory: "魔法珍品", traits: [], description: "", source: "焦土世界 - 传诵镇", base_buzz: 24, max_buzz: 118, max_knowledge: 0 },
  { id: "251", name: "鸡图腾柱", category: "奇幻", subcategory: "魔法珍品", traits: [], description: "", source: "焦土世界 - 雷诺神殿", base_buzz: 30, max_buzz: 130, max_knowledge: 0 },
  { id: "252", name: "愚人宝箱", category: "奇幻", subcategory: "魔法珍品", traits: ["神奇魔法", "饥饿的宝藏"], description: "", source: "焦土世界 - 菜鸟之翼", base_buzz: 30, max_buzz: 130, max_knowledge: 0 },
  { id: "253", name: "精灵神壶", category: "奇幻", subcategory: "魔法珍品", traits: [], description: "", source: "焦土世界 - 仙灵谷, 积云森林", base_buzz: 20, max_buzz: 110, max_knowledge: 0 },
  { id: "254", name: "二十面命运", category: "奇幻", subcategory: "魔法珍品", traits: ["神奇魔法"], description: "20点：用魅力吸引访客，提升他们的热议度和移动速度。靠近被吸引的访客时，其他访客会感同身受并提升幸福感\n19点：提升来自访客的捐款\n18点：提升奇幻专家的力量和幸福感。\n17点：提升奇幻专家的智力和访客的知识。\n16点：提升二十面命运的热议度（+10）\n15点：二十面命运周围的奇幻展示品清洁度降低减缓。\n14点：二十面命运可实现精灵神壶的愿望。\n13点：二十面命运的清洁度降低速度减缓25%。\n12点：提升精灵访客的幸福度\n11点：提升矮人访客的幸福度\n10点：这只是一个平凡的骰子，无事发生。\n9点：提升访客速度，但降低访客能量。\n8点：提升员工幸福感，但降低奇幻属性。\n7点：降低肠胃舒适度，提升吃饱度和喝饱度\n6点：二十面命运的清洁度降低速度提升25%。\n5点：降低奇幻专家的力量。\n4点：有几率让哥布林访客迷失善念。\n3点：降低能量和移动速度。\n2点：降低访客热议度（-5%）\n1点：可能会导致访客立即离开博物馆。", source: "其他", base_buzz: 75, max_buzz: 220, max_knowledge: 0 },
  // --- 奇幻 / 奇幻世界遗物 ---
  { id: "255", name: "猫骑士雕像", category: "奇幻", subcategory: "奇幻世界遗物", traits: [], description: "", source: "焦土世界 - 传诵镇", base_buzz: 9, max_buzz: 88, max_knowledge: 0 },
  { id: "256", name: "武器圆桌", category: "奇幻", subcategory: "奇幻世界遗物", traits: [], description: "", source: "焦土世界 - 晦暗之城", base_buzz: 18, max_buzz: 106, max_knowledge: 0 },
  { id: "257", name: "恶魔之门", category: "奇幻", subcategory: "奇幻世界遗物", traits: [], description: "", source: "焦土世界 - 雷诺神殿", base_buzz: 27, max_buzz: 124, max_knowledge: 0 },
  { id: "258", name: "消防马车", category: "奇幻", subcategory: "奇幻世界遗物", traits: [], description: "", source: "焦土世界 - 浓烟草原", base_buzz: 12, max_buzz: 94, max_knowledge: 0 },
  { id: "259", name: "童话衣柜", category: "奇幻", subcategory: "奇幻世界遗物", traits: [], description: "", source: "焦土世界 - 幻境集市", base_buzz: 35, max_buzz: 140, max_knowledge: 0 },
  { id: "260", name: "地下城指南", category: "奇幻", subcategory: "奇幻世界遗物", traits: [], description: "", source: "焦土世界 - 晦暗之城", base_buzz: 38, max_buzz: 146, max_knowledge: 0 },
  { id: "261", name: "奇幻盔甲", category: "奇幻", subcategory: "奇幻世界遗物", traits: [], description: "", source: "焦土世界 - 海文哈夫王城", base_buzz: 26, max_buzz: 122, max_knowledge: 0 },
  { id: "262", name: "奇幻雕像", category: "奇幻", subcategory: "奇幻世界遗物", traits: [], description: "", source: "焦土世界 - 菜鸟之翼", base_buzz: 8, max_buzz: 86, max_knowledge: 0 },
  { id: "263", name: "海文哈夫挂毯", category: "奇幻", subcategory: "奇幻世界遗物", traits: ["无"], description: "", source: "焦土世界 - 海文哈夫王城, 祈愿村", base_buzz: 10, max_buzz: 90, max_knowledge: 0 },
  { id: "264", name: "三手大剑", category: "奇幻", subcategory: "奇幻世界遗物", traits: ["无"], description: "", source: "焦土世界 - 仙灵谷, 浓烟草原", base_buzz: 18, max_buzz: 106, max_knowledge: 0 },
  { id: "265", name: "巨魔石像", category: "奇幻", subcategory: "奇幻世界遗物", traits: [], description: "", source: "焦土世界 - 巨魔之桥", base_buzz: 12, max_buzz: 94, max_knowledge: 0 },
  { id: "266", name: "龙尾异闻录", category: "奇幻", subcategory: "奇幻世界遗物", traits: ["唯一"], description: "", source: "焦土世界 - 被摧毁的仙灵谷", base_buzz: 50, max_buzz: 170, max_knowledge: 0 },
  { id: "267", name: "战争残垣", category: "奇幻", subcategory: "奇幻世界遗物", traits: ["无"], description: "", source: "焦土世界 - 被摧毁的仙灵谷", base_buzz: 26, max_buzz: 122, max_knowledge: 0 },
  { id: "268", name: "龙鳞秤", category: "奇幻", subcategory: "奇幻世界遗物", traits: ["无"], description: "", source: "焦土世界 - 幻境集市", base_buzz: 34, max_buzz: 138, max_knowledge: 0 },
  { id: "269", name: "头铁王座", category: "奇幻", subcategory: "奇幻世界遗物", traits: ["无"], description: "", source: "焦土世界 - 颠倒镇", base_buzz: 33, max_buzz: 136, max_knowledge: 0 },
  // --- 奇幻 / 矮人装置 ---
  { id: "270", name: "闪光晶矿", category: "奇幻", subcategory: "矮人装置", traits: ["晶矿原石"], description: "", source: "焦土世界 - 颠倒镇", base_buzz: 10, max_buzz: 90, max_knowledge: 0 },
  { id: "271", name: "草之晶矿", category: "奇幻", subcategory: "矮人装置", traits: ["晶矿原石"], description: "", source: "焦土世界 - 无穷矿洞", base_buzz: 10, max_buzz: 90, max_knowledge: 0 },
  { id: "272", name: "水之晶矿", category: "奇幻", subcategory: "矮人装置", traits: ["晶矿原石"], description: "", source: "焦土世界 - 无穷矿洞", base_buzz: 10, max_buzz: 90, max_knowledge: 0 },
  { id: "273", name: "火之晶矿", category: "奇幻", subcategory: "矮人装置", traits: ["晶矿原石"], description: "", source: "焦土世界 - 无穷矿洞", base_buzz: 10, max_buzz: 90, max_knowledge: 0 },
  { id: "274", name: "水之宝石", category: "奇幻", subcategory: "矮人装置", traits: ["无"], description: "", source: "其他", base_buzz: 51, max_buzz: 172, max_knowledge: 0 },
  { id: "275", name: "草之宝石", category: "奇幻", subcategory: "矮人装置", traits: ["无"], description: "", source: "其他", base_buzz: 54, max_buzz: 178, max_knowledge: 0 },
  { id: "276", name: "火之宝石", category: "奇幻", subcategory: "矮人装置", traits: ["无"], description: "", source: "其他", base_buzz: 52, max_buzz: 174, max_knowledge: 0 },
  { id: "277", name: "瓦斯装置", category: "奇幻", subcategory: "矮人装置", traits: ["瓦斯装置"], description: "", source: "焦土世界 - 大矮人港", base_buzz: 20, max_buzz: 110, max_knowledge: 0 },
  { id: "278", name: "火焰装置", category: "奇幻", subcategory: "矮人装置", traits: ["火焰装置"], description: "", source: "焦土世界 - 齿轮天塔", base_buzz: 22, max_buzz: 114, max_knowledge: 0 },
  { id: "279", name: "族风装置", category: "奇幻", subcategory: "矮人装置", traits: ["族风装置"], description: "", source: "焦土世界 - 齿轮天塔", base_buzz: 17, max_buzz: 104, max_knowledge: 0 },
  { id: "280", name: "熔炼装詈", category: "奇幻", subcategory: "矮人装置", traits: ["熔炼装詈"], description: "", source: "焦土世界 - 大矮人港", base_buzz: 34, max_buzz: 138, max_knowledge: 0 },
  { id: "281", name: "晶矿装置", category: "奇幻", subcategory: "矮人装置", traits: ["晶矿装置"], description: "", source: "焦土世界 - 大矮人港", base_buzz: 28, max_buzz: 126, max_knowledge: 0 },
  // --- 奇幻 / 神话装备 ---
  { id: "282", name: "唠叨巫师帽", category: "奇幻", subcategory: "神话装备", traits: ["员工装备", "魔法学院之声", "唯一"], description: "", source: "焦土世界 - 魔尊之巅", base_buzz: 61, max_buzz: 192, max_knowledge: 0 },
  { id: "283", name: "鲁特宝琴", category: "奇幻", subcategory: "神话装备", traits: ["员工装备", "金曲点唱机", "唯一"], description: "", source: "焦土世界 - 醉哥酒馆", base_buzz: 57, max_buzz: 184, max_knowledge: 0 },
  { id: "284", name: "诺尔之锤", category: "奇幻", subcategory: "神话装备", traits: ["员工装备", "手到擒来"], description: "", source: "焦土世界 - 暴怒熔炉", base_buzz: 65, max_buzz: 200, max_knowledge: 0 },
  { id: "285", name: "暴速飞靴", category: "奇幻", subcategory: "神话装备", traits: ["员工装备", "轻羽步伐"], description: "", source: "焦土世界 - 祈愿村, 颠倒镇", base_buzz: 24, max_buzz: 118, max_knowledge: 0 },
  { id: "286", name: "主角光环盔甲", category: "奇幻", subcategory: "神话装备", traits: ["员工装备", "既定天命"], description: "", source: "焦土世界 - 长途旅店", base_buzz: 68, max_buzz: 206, max_knowledge: 0 },
  { id: "287", name: "王国之冠", category: "奇幻", subcategory: "神话装备", traits: ["员工装备", "王冠明珠"], description: "", source: "焦土世界 - 阴云山", base_buzz: 100, max_buzz: 270, max_knowledge: 0 },
  { id: "288", name: "独眼帽", category: "奇幻", subcategory: "神话装备", traits: ["员工装备", "目光如炬"], description: "", source: "焦土世界 - 巨魔之桥", base_buzz: 55, max_buzz: 180, max_knowledge: 0 },
  { id: "289", name: "石面具", category: "奇幻", subcategory: "神话装备", traits: [], description: "", source: "数码宇宙 - 锦钿书库", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "290", name: "菠菜", category: "奇幻", subcategory: "神话装备", traits: [], description: "", source: "数码宇宙 - 大教堂", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "291", name: "大蒜", category: "奇幻", subcategory: "神话装备", traits: [], description: "", source: "数码宇宙 - 疯狂森林", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "292", name: "圣徒水", category: "奇幻", subcategory: "神话装备", traits: [], description: "", source: "数码宇宙 - 大教堂", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "293", name: "月桂", category: "奇幻", subcategory: "神话装备", traits: [], description: "", source: "数码宇宙 - 锦钿书库", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "294", name: "四叶草", category: "奇幻", subcategory: "神话装备", traits: [], description: "", source: "数码宇宙 - 疯狂森林", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  // --- 奇幻 / 互动式展示品 ---
  { id: "295", name: "地下城跑酷迷宫", category: "奇幻", subcategory: "互动式展示品", traits: ["无"], description: "", source: "焦土世界 - 工作坊", base_buzz: 60, max_buzz: 160, max_knowledge: 0 },
  { id: "296", name: "擂台王", category: "奇幻", subcategory: "互动式展示品", traits: ["无"], description: "", source: "焦土世界 - 工作坊", base_buzz: 20, max_buzz: 80, max_knowledge: 0 },
  // --- 野生动物 ---
  { id: "297", name: "折纹斑马", category: "野生动物", subcategory: "大型哺乳类", traits: ["栖息地", "沙漠", "草食", "稀疏"], description: "", source: "远方群岛 - 热界线", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "298", name: "无骨蟾蜍", category: "野生动物", subcategory: "爬行类", traits: ["生态箱", "丛林"], description: "", source: "远方群岛 - 远方丛林", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "299", name: "蛇咬蛇", category: "野生动物", subcategory: "爬行类", traits: ["生态箱", "丛林"], description: "", source: "远方群岛 - 黏沼密林", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "300", name: "方狐", category: "野生动物", subcategory: "犬科", traits: ["栖息地", "极地", "肉食", "密集"], description: "", source: "远方群岛 - 远方悬崖", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "301", name: "超音狼", category: "野生动物", subcategory: "犬科", traits: ["栖息地", "洞穴", "肉食", "稀疏"], description: "", source: "远方群岛 - 远方洞穴", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "302", name: "冬日衫毛羊", category: "野生动物", subcategory: "大型哺乳类", traits: ["栖息地", "极地", "草食", "空旷"], description: "", source: "白骨带 - 衫毛羊冰原", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "303", name: "远方高山羊", category: "野生动物", subcategory: "大型哺乳类", traits: ["栖息地", "极地", "草食", "稀疏"], description: "", source: "远方群岛 - 冷冽溪流", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "304", name: "跳跳衫毛羊", category: "野生动物", subcategory: "大型哺乳类", traits: ["栖息地", "极地", "草食", "空旷"], description: "", source: "远方群岛 - 冷冽溪流", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "305", name: "弹跳羚", category: "野生动物", subcategory: "大型哺乳类", traits: ["栖息地", "沙漠", "草食", "空旷"], description: "", source: "远方群岛 - 雄狮平原", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "306", name: "嗅嗅貘", category: "野生动物", subcategory: "大型哺乳类", traits: ["栖息地", "丛林", "草食", "稀疏"], description: "", source: "远方群岛 - 雄狮平原", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "307", name: "金松露猪", category: "野生动物", subcategory: "大型哺乳类", traits: ["栖息地", "洞穴", "草食", "稀疏"], description: "", source: "远方群岛 - 荒野深渊", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "308", name: "长弹簧鹿", category: "野生动物", subcategory: "大型哺乳类", traits: ["栖息地", "沙漠", "草食", "稀疏"], description: "", source: "远方群岛 - 热界线", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "309", name: "疯癫鹤", category: "野生动物", subcategory: "鸟类", traits: ["栖息地", "沙漠", "肉食", "稀疏"], description: "", source: "远方群岛 - 干旱草原", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "310", name: "纸鹤", category: "野生动物", subcategory: "鸟类", traits: ["生态箱", "草原"], description: "", source: "远方群岛 - 淘金河溪", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "311", name: "嗡嗡鸟", category: "野生动物", subcategory: "鸟类", traits: ["生态箱", "草原"], description: "", source: "远方群岛 - 孢子花园", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "312", name: "滚石企鹅", category: "野生动物", subcategory: "鸟类", traits: ["栖息地", "极地", "肉食", "空旷"], description: "", source: "远方群岛 - 冰川洼地", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "313", name: "食肉鹫", category: "野生动物", subcategory: "鸟类", traits: ["栖息地", "丛林", "肉食", "密集"], description: "", source: "远方群岛 - 远方丛林", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "314", name: "潇洒狮", category: "野生动物", subcategory: "猫科", traits: ["栖息地", "沙漠", "肉食", "稀疏"], description: "", source: "远方群岛 - 雄狮平原", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "315", name: "迷幻虎", category: "野生动物", subcategory: "猫科", traits: ["栖息地", "丛林", "肉食", "密集"], description: "", source: "远方群岛 - 吞没小径", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "316", name: "鱼狮", category: "野生动物", subcategory: "猫科", traits: ["栖息地", "草原", "肉食", "稀疏"], description: "", source: "远方群岛 - 远方绿地", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "317", name: "猎头树熊", category: "野生动物", subcategory: "熊科", traits: ["栖息地", "丛林", "肉食", "密集"], description: "", source: "远方群岛 - 吞没小径", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "318", name: "眼影熊猫", category: "野生动物", subcategory: "熊科", traits: ["栖息地", "丛林", "草食", "密集"], description: "", source: "远方群岛 - 憨憨竹林", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "319", name: "彩环仓鼠", category: "野生动物", subcategory: "小型哺乳类", traits: ["生态箱", "草原"], description: "", source: "远方群岛 - 孢子花园", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "320", name: "树皮土豚", category: "野生动物", subcategory: "小型哺乳类", traits: ["栖息地", "草原", "草食", "稀疏"], description: "", source: "远方群岛 - 蜿蜒草甸", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "321", name: "淡定水豚", category: "野生动物", subcategory: "小型哺乳类", traits: ["栖息地", "任意", "草食", "任意"], description: "", source: "远方群岛 - 蜿蜒草甸", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "322", name: "蓝刺猬", category: "野生动物", subcategory: "小型哺乳类", traits: ["生态箱", "极地"], description: "", source: "远方群岛 - 石楠冻原", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "323", name: "月肚鼹鼠", category: "野生动物", subcategory: "小型哺乳类", traits: ["生态箱", "洞穴"], description: "", source: "远方群岛 - 荒野深渊", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "324", name: "仙人掌花蝎", category: "野生动物", subcategory: "昆虫", traits: ["生态箱", "沙漠"], description: "", source: "远方群岛 - 远方沙漠", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "325", name: "雨滴圣甲虫", category: "野生动物", subcategory: "昆虫", traits: ["生态箱", "沙漠"], description: "", source: "远方群岛 - 远方沙漠", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "326", name: "飞机蜢", category: "野生动物", subcategory: "昆虫", traits: ["生态箱", "沙漠"], description: "", source: "远方群岛 - 干旱草原", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "327", name: "雪球蛾", category: "野生动物", subcategory: "昆虫", traits: ["生态箱", "极地"], description: "", source: "远方群岛 - 石楠冻原", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "328", name: "放屁虫", category: "野生动物", subcategory: "昆虫", traits: ["生态箱", "洞穴"], description: "", source: "远方群岛 - 远方洞穴", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "329", name: "小屋蜗牛", category: "野生动物", subcategory: "昆虫", traits: ["生态箱", "任意"], description: "", source: "远方群岛 - 黏沼密林", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "330", name: "银背连眉怪", category: "野生动物", subcategory: "昆虫", traits: ["生态箱", "丛林"], description: "", source: "白骨带 - 银背沼泽", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "331", name: "阳咬蛇", category: "野生动物", subcategory: "爬行类", traits: ["生态箱", "沙漠"], description: "", source: "远方群岛 - 远方沙漠", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "332", name: "胡须蜥蜴", category: "野生动物", subcategory: "爬行类", traits: ["生态箱", "丛林"], description: "", source: "远方群岛 - 永雾森林", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "333", name: "随心龙", category: "野生动物", subcategory: "爬行类", traits: ["生态箱", "丛林"], description: "", source: "远方群岛 - 永雾森林", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "334", name: "休战蛇", category: "野生动物", subcategory: "爬行类", traits: ["生态箱", "草原"], description: "", source: "远方群岛 - 淘金河溪", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "335", name: "蛮牛蛙", category: "野生动物", subcategory: "爬行类", traits: ["生态箱", "草原"], description: "", source: "远方群岛 - 远方绿地", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "336", name: "菜园龟", category: "野生动物", subcategory: "爬行类", traits: ["栖息地", "草原", "草食", "空旷"], description: "", source: "远方群岛 - 远方绿地", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "337", name: "宠物石", category: "野生动物", subcategory: "爬行类", traits: ["生态箱", "任意"], description: "", source: "远方群岛 - 随机事件", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "338", name: "霜咬蛇", category: "野生动物", subcategory: "爬行类", traits: ["生态箱", "极地"], description: "", source: "远方群岛 - 远方悬崖", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "339", name: "夜咬蛇", category: "野生动物", subcategory: "爬行类", traits: ["生态箱", "洞穴"], description: "", source: "远方群岛 - 荒野深渊", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "340", name: "潇洒狮合影站", category: "野生动物", subcategory: "互动式展示品", traits: [], description: "", source: "其他 - 工作坊", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "341", name: "弹跳羚摇马", category: "野生动物", subcategory: "互动式展示品", traits: [], description: "", source: "其他 - 工作坊", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "342", name: "蛇形滑梯", category: "野生动物", subcategory: "互动式展示品", traits: [], description: "", source: "其他 - 工作坊", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "343", name: "礼物投放机", category: "野生动物", subcategory: "互动式展示品", traits: [], description: "", source: "其他 - 工作坊", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  // --- 其他 / 赞助商展示品 ---
  { id: "344", name: "低端科技宣传盒", category: "其他", subcategory: "赞助商展示品", traits: ["低端又无趣"], description: "好吧，又一件低端科技的玩意……", source: "低端科技地穴", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "345", name: "捣泥艺术节宣传牌", category: "其他", subcategory: "赞助商展示品", traits: ["赞助商内容"], description: "", source: "其他", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  // --- 其他 / 奖励展示品 ---
  { id: "346", name: "印钱机", category: "其他", subcategory: "奖励展示品", traits: ["杜绝脏污", "无需维护"], description: "", source: "其他", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "347", name: "贾思敏专辑", category: "其他", subcategory: "奖励展示品", traits: ["杜绝脏污", "无需维护"], description: "", source: "其他", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  // --- 其他 / 冬季快闪 ---
  { id: "348", name: "彩球鱼", category: "其他", subcategory: "冬季快闪", traits: [], description: "", source: "白骨带", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "349", name: "冰封姜饼水晶球", category: "其他", subcategory: "冬季快闪", traits: [], description: "", source: "白骨带", base_buzz: 0, max_buzz: 0, max_knowledge: 0 },
  { id: "350", name: "闪亮煎香肠树", category: "其他", subcategory: "冬季快闪", traits: [], description: "", source: "白骨带", base_buzz: 0, max_buzz: 0, max_knowledge: 0 }
];

